[general]
import = [
  "~/.config/alacritty/themes/themes/duskfox.toml",
]

[window]
dimensions = {columns = 120, lines = 30}
opacity = 0.725
option_as_alt = "Both"
padding = {x = 4, y = 2}

[scrolling]
history = 100000
multiplier = 5

[font]
bold = {family = "Hack Nerd Font", style = "Bold"}
bold_italic = {family = "Hack Nerd Font", style = "Bold Italic"}
italic = {family = "Hack Nerd Font", style = "Italic"}
normal = {family = "Hack Nerd Font", style = "Regular"}
offset = {x = 0, y = 4}
size = 12.0

[terminal]
shell = {program = "/bin/zsh", args = ["-l", "-c", "zellij"]}

[keyboard]
# see https://zenn.dev/cp_r/articles/01469ecbd1a5ac
bindings = [
  {key = "\\", mods = "Command", chars = "\u001b[118;3u"}, # alt+v
  {key = "|", mods = "Command|Shift", chars = "\u001b[104;3u"}, # alt+h
  {key = "t", mods = "Command", chars = "\u001b[116;3u"}, # alt+h
  {key = "w", mods = "Command", chars = "\u001b[120;3u"}, # alt+x
  {key = "m", mods = "Command", chars = "\u001b[109;3u"}, # alt+m
  {key = "Tab", mods = "Control", chars = "\u001b[91;5u"}, # ctrl+[
  {key = "Tab", mods = "Control|Shift", chars = "\u001b[93;5u"}, # ctrl+]
  {key = "ArrowUp", mods = "Command", chars = "\u001b[73;5u"}, # ctrl+u
  {key = "ArrowDown", mods = "Command", chars = "\u001b[75;5u"}, # ctrl+d
]
